In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess= tf.Session()

In [3]:
id_matrix = tf.diag([1.0,1.0,1.0])
sess.run(id_matrix)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [4]:
#rand norm matrix

Ran_ma = tf.truncated_normal([2,3])
sess.run(Ran_ma)

array([[-0.85074806, -0.09939841, -1.3248619 ],
       [-0.28879103,  0.8085931 , -0.2140743 ]], dtype=float32)

In [5]:
#constant matrix
con_ma = tf.fill([2,3],5)
sess.run(con_ma)

array([[5, 5, 5],
       [5, 5, 5]])

In [6]:
a = tf.random_uniform([2,3])
sess.run(a)

array([[0.93767893, 0.35377717, 0.62704825],
       [0.740834  , 0.83225834, 0.36925995]], dtype=float32)

In [9]:
d= tf.convert_to_tensor(np.array([[1.0,2.0,3.0],[4.0,5.0,6.0],[6.0,7.0,8.0]]), dtype=tf.float32)
sess.run(d)

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]], dtype=float32)

In [10]:
e = tf.matmul(d,id_matrix)
sess.run(e)

array([[1., 2., 3.],
       [4., 5., 6.],
       [6., 7., 8.]], dtype=float32)

In [11]:
sess.run(tf.self_adjoint_eig(d))

(array([-2.446337  , -0.45941347, 16.90575   ], dtype=float32),
 array([[ 0.8652531 ,  0.2857136 ,  0.4119523 ],
        [ 0.006452  , -0.82798845,  0.56070817],
        [-0.50129366,  0.48249644,  0.71826315]], dtype=float32))

In [12]:
sess.run(tf.self_adjoint_eigvals(d))

array([-2.446337  , -0.45941347, 16.90575   ], dtype=float32)

In [13]:
sess.run(tf.constant(100))

100

In [14]:
sess.run(tf.constant([1,2,3]))

array([1, 2, 3])

In [16]:
#x = tf.placeholder(shape=[3,2], dtype=tf.float32)
#sess.run(x)

In [18]:
#y = tf.Variable(shape=[3,2], dtype=tf.float32)

#init = tf.global_variables_initializer()
#sess.run(init,y)